### PR TITLE
Added organisationLogo URL

### PR DESCRIPTION
**Pull request by Kashish0423**
Hello @Manvityagi  mam , I tried to test using npm test as I also mentioned in my comment on the issue, it's giving compilation error so I guess there is some error there , i tried to add the field where i found it to be added , if I need to add it anywhere else or remove from some place do let me know

### CODE REVIEW

**Comment by Manvityagi** [comment]
> Hello @Manvityagi mam , I tried to test using npm test as I also mentioned in my comment on the issue, it's giving compilation error so I guess there is some error there , i tried to add the field where i found it to be added , if I need to add it anywhere else or remove from some place do let me know

Pull the latest code, the issue has been fixed

**Comment by Kashish0423** [comment]
> > Hello @Manvityagi mam , I tried to test using npm test as I also mentioned in my comment on the issue, it's giving compilation error so I guess there is some error there , i tried to add the field where i found it to be added , if I need to add it anywhere else or remove from some place do let me know
> 
> Pull the latest code, the issue has been fixed

okay , working on it

**Comment by Kashish0423** [comment]
Opportunity_cal_npm_test_error

This error still persists like before , am I missing something ?

**Review by Manvityagi — APPROVED** [review]

**Comment by Manvityagi** [comment]
Fixed #65

**Review by Manvityagi — APPROVED** [review]

**Pull request merged**
